version: "3.4"
services:
  ssl:
    image: itzg/openssl-ubuntu:latest
    volumes:
      - canxium:/canxium
    command: rand -hex 32 | tr -d "\n" > "/canxium/jwt.hex"

  init:
    image: canxium/go-canxium:v0.2.3
    depends_on:
      ssl:
        condition: service_completed_successfully
    volumes:
      - canxium:/canxium
    command: --datadir=/canxium --db.engine=pebble init /genesis/mainnet.genesis.json

  canxium:
    image: canxium/go-canxium:v0.2.3
    restart: always
    volumes:
      - canxium:/canxium
    depends_on:
      init:
        condition: service_completed_successfully
    ports:
      - "30303:30303"
    healthcheck:
      test: curl --location http://127.0.0.1:8545 || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
    command: --http --db.engine=pebble --syncmode full --authrpc.addr 0.0.0.0 --authrpc.jwtsecret=/canxium/jwt.hex --authrpc.vhosts=canxium --networkid 3003 --datadir /canxium --bootnodes enode://314f1041da4b27f5e4c02b4eac52ca7bd2f025cb585490cb7032fdb08db737aa10d7d64a780db697643ece6027d3bc1a511696420e76192648c0d2d74d099c73@boot.canxium.net:30303,enode://767d3e408b073ca501ea7336096c048eea46513ac5c44659ac902d7575881ca114c82277dff7826630ec9fb45d8cfa5a82b9eacc8b477dc475746eaec39e2f2a@boot.canxium.org:30303,enode://f06de34b87954abb25be2e8d592306bc55b396a4eead839dba90baf4e59465d3ef704866962cf2fd995e6ce04f17de31edebb11afcac9df4eaea847f35e3cbaf@boot-n2.canxium.org:30303

  beacon_node:
    image: canxium/lodestar:v1.17.0
    restart: always
    volumes:
      - beacon_node:/data
      - canxium:/canxium
      - logs:/logs
    ports:
      - "9000:9000" # P2P port
      - "9596:9596" # API port
    depends_on:
      ssl:
        condition: service_completed_successfully
      canxium:
        condition: service_started
    command: beacon --network canxium --dataDir /data --rest --rest.address 0.0.0.0 --metrics --logFile /logs/beacon.log --logFileLevel info --logLevel info --logFileDailyRotate 5 --jwtSecret /canxium/jwt.hex --execution.urls http://canxium:8551 --checkpointSyncUrl https://beacon-api.canxium.org
    environment:
      NODE_OPTIONS: --max-old-space-size=8192

  validator:
    image: canxium/lodestar:v1.17.0
    restart: always
    volumes:
      - validator:/data
      - logs:/logs
      - ./keystores:/keystores
    depends_on:
      beacon_node:
        condition: service_started
    command: validator --network canxium --suggestedFeeRecipient 0x0000000000000000000000000000000000000000 --dataDir /data --importKeystores /keystores --importKeystoresPassword /keystores/password.txt --server http://beacon_node:9596 --logFile /logs/validator.log --logFileLevel info --logFileDailyRotate 5
    environment:
      NODE_OPTIONS: --max-old-space-size=2048

volumes:
  validator:
  logs:
  canxium:
  beacon_node:
